# Generated by Django 6.0.1 on 2026-01-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Office', 'Office'), ('Shop', 'Shop'), ('Warehouse', 'Warehouse')], max_length=20)),
                ('area_sqft', models.PositiveIntegerField()),
                ('furnishing', models.CharField(blank=True, max_length=50)),
                ('parking', models.CharField(blank=True, max_length=50)),
                ('washrooms', models.PositiveIntegerField(default=1)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('total_floors', models.CharField(blank=True, max_length=20)),
                ('suitable_for', models.CharField(blank=True, max_length=200)),
                ('maintenance', models.CharField(blank=True, max_length=100)),
                ('possession', models.CharField(blank=True, max_length=100)),
                ('property_age', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('requirement', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.property')),
            ],
        ),
    ]
